name: Run Tests

on: push

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Compile
        run:  make
      - name: Run Tests
        run:  bash tests/test.sh
      - name: Clean Up
        run:  make clean